apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trivial-go-web-app
  template:
    metadata:
      labels:
        app: trivial-go-web-app
    spec:
      containers:
        - name: webserver-simple
          image: d868143226472.dkr.ecr.eu-west-1.amazonaws.com/tolrendor-software/simple-web-app:f4e1280
          ports:
            - containerPort: 8080
