---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivial-go-web-app
  template:
    metadata:
      labels:
        app: trivial-go-web-app
    spec:
      containers:
      - name: webserver-simple
        image: 868143226472.dkr.ecr.eu-west-1.amazonaws.com/tolrendor-software/simple-web-app:84f63fc
        ports:
        - containerPort: 8080
